#!/usr/bin/env python3
"""Generate the GitHub Copilot model catalog from the official GitHub Docs tables."""

from __future__ import annotations

import argparse
import datetime as dt
import json
import pathlib
import urllib.request

import yaml


DOCS_BASE = "https://raw.githubusercontent.com/github/docs/main/data/tables/copilot"
SOURCES = {
    "release": f"{DOCS_BASE}/model-release-status.yml",
    "cli": f"{DOCS_BASE}/auto-model-selection.yml",
    "deprecation": f"{DOCS_BASE}/model-deprecation-history.yml",
}


def load_yaml(path: pathlib.Path) -> list[dict]:
    with path.open(encoding="utf-8") as stream:
        value = yaml.safe_load(stream)
    if not isinstance(value, list) or not all(isinstance(item, dict) for item in value):
        raise ValueError(f"{path} does not contain a YAML list of objects")
    return value


def refresh(data_dir: pathlib.Path) -> None:
    data_dir.mkdir(parents=True, exist_ok=True)
    for name, url in SOURCES.items():
        urllib.request.urlretrieve(url, data_dir / f"{name}.yml")


def cli_status(model: dict, cli_models: dict[str, dict]) -> str:
    entry = cli_models.get(model["name"])
    if entry is None:
        return "Not listed"
    return "Yes" if entry.get("cli") is True else "No"


def catalog_data(release: list[dict], cli: list[dict], deprecation: list[dict]) -> dict:
    cli_models = {model["name"]: model for model in cli}
    today = dt.date.today()
    return {
        "supported": [
            {
                "name": model["name"],
                "provider": model["provider"],
                "releaseStatus": model["release_status"],
                "copilotCli": cli_status(model, cli_models),
            }
            for model in release
        ],
        "deprecated": [
            {
                "name": model["name"],
                "retirementDate": model["retirement_date"],
                "status": (
                    "Scheduled"
                    if dt.date.fromisoformat(model["retirement_date"]) >= today
                    else "Retired"
                ),
                "suggestedAlternative": model["suggested_alternative"],
            }
            for model in deprecation
        ],
    }


def render(catalog: dict) -> str:
    lines = [
        "# GitHub Copilot model catalog",
        "",
        "> Generated by [`scripts/update_copilot_model_catalog.py`](../scripts/update_copilot_model_catalog.py) "
        "from the official [GitHub Docs model tables][release-source].",
        "> This is the provider-wide catalog, not an entitlement check for the current user or organization.",
        "> Use `model-evaluator list-models --probe` for a zero-usage check against this catalog.",
        "",
        "## Currently supported models",
        "",
        "| Model | Provider | Release status | Copilot CLI |",
        "| --- | --- | --- | --- |",
    ]
    for model in catalog["supported"]:
        lines.append(
            f"| {model['name']} | {model['provider']} | {model['releaseStatus']} "
            f"| {model['copilotCli']} |"
        )

    lines.extend(
        [
            "",
            "## Deprecated or retired models",
            "",
            "| Model | Retirement date | Status | Suggested alternative |",
            "| --- | --- | --- | --- |",
        ]
    )
    for model in catalog["deprecated"]:
        lines.append(
            f"| {model['name']} | {model['retirementDate']} | {model['status']} "
            f"| {model['suggestedAlternative']} |"
        )

    lines.extend(
        [
            "",
            "The supported table reflects GitHub's published model release status. The CLI column "
            "comes from GitHub's Copilot model-surface table; `Not listed` is not proof that a model "
            "is unavailable in a particular CLI version. Availability also depends on plan, "
            "organization policy, geography, and rollout state. Retirement history can also include "
            "plan-specific exceptions documented by GitHub.",
            "",
            "[release-source]: https://github.com/github/docs/blob/main/data/tables/copilot/model-release-status.yml",
            "[cli-source]: https://github.com/github/docs/blob/main/data/tables/copilot/auto-model-selection.yml",
            "[deprecation-source]: https://github.com/github/docs/blob/main/data/tables/copilot/model-deprecation-history.yml",
        ]
    )
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--data-dir", type=pathlib.Path, default=pathlib.Path("build/copilot-model-data"))
    parser.add_argument("--output", type=pathlib.Path, default=pathlib.Path("docs/copilot-models.md"))
    parser.add_argument(
        "--json-output",
        type=pathlib.Path,
        default=pathlib.Path("src/ModelEvaluator.Core/Data/copilot-model-catalog.json"),
    )
    parser.add_argument("--refresh", action="store_true", help="Download the latest official source tables.")
    args = parser.parse_args()

    if args.refresh:
        refresh(args.data_dir)

    release = load_yaml(args.data_dir / "release.yml")
    cli = load_yaml(args.data_dir / "cli.yml")
    deprecation = load_yaml(args.data_dir / "deprecation.yml")
    catalog = catalog_data(release, cli, deprecation)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render(catalog), encoding="utf-8")
    args.json_output.parent.mkdir(parents=True, exist_ok=True)
    args.json_output.write_text(
        json.dumps(catalog, indent=2, ensure_ascii=True) + "\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
