<Project>
  <PropertyGroup>
    <Version>0.1.0</Version>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <RepositoryUrl>https://github.com/sujithq/model-evaluator</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>
</Project>
